// AUTO-GENERATED — DO NOT EDIT
// Run `npm run generate:registry` to regenerate this file.

export const TOKEN_DEFAULTS: Record<string, string> = {
  "--color-black": "#121212",
  "--color-white": "#fff",
  "--color-yellow": "#EBCB8B",
  "--color-red": "#BF616A",
  "--color-green": "#A3BE8C",
  "--color-neutral-0": "var(--color-white)",
  "--color-neutral-1": "color-mix(in oklch, var(--color-neutral-10) 10%, var(--color-white))",
  "--color-neutral-2": "color-mix(in oklch, var(--color-neutral-10) 20%, var(--color-white))",
  "--color-neutral-3": "color-mix(in oklch, var(--color-neutral-10) 30%, var(--color-white))",
  "--color-neutral-4": "color-mix(in oklch, var(--color-neutral-10) 40%, var(--color-white))",
  "--color-neutral-5": "color-mix(in oklch, var(--color-neutral-10) 50%, var(--color-white))",
  "--color-neutral-6": "color-mix(in oklch, var(--color-neutral-10) 60%, var(--color-white))",
  "--color-neutral-7": "color-mix(in oklch, var(--color-neutral-10) 70%, var(--color-white))",
  "--color-neutral-8": "color-mix(in oklch, var(--color-neutral-10) 80%, var(--color-white))",
  "--color-neutral-9": "color-mix(in oklch, var(--color-neutral-10) 90%, var(--color-white))",
  "--color-neutral-10": "var(--color-black)",
  "--color-primary": "#81A1C1",
  "--color-primary-light": "oklch(from var(--color-primary) calc(l + 0.15) c h)",
  "--color-primary-dark": "oklch(from var(--color-primary) calc(l - 0.15) c h)",
  "--color-primary-light-contrast": "var(--color-white)",
  "--color-primary-dark-contrast": "var(--color-white)",
  "--color-secondary": "#B48EAD",
  "--color-secondary-light": "oklch(from var(--color-secondary) calc(l + 0.15) c h)",
  "--color-secondary-dark": "oklch(from var(--color-secondary) calc(l - 0.15) c h)",
  "--color-secondary-light-contrast": "var(--color-white)",
  "--color-secondary-dark-contrast": "var(--color-white)",
  "--color-tertiary": "#f1be5f",
  "--color-tertiary-light": "oklch(from var(--color-tertiary) calc(l + 0.15) c h)",
  "--color-tertiary-dark": "oklch(from var(--color-tertiary) calc(l - 0.15) c h)",
  "--color-tertiary-light-contrast": "var(--color-white)",
  "--color-tertiary-dark-contrast": "var(--color-white)",
  "--color-action": "var(--color-primary)",
  "--color-action-light": "oklch(from var(--color-action) calc(l + 0.15) c h)",
  "--color-action-dark": "oklch(from var(--color-action) calc(l - 0.15) c h)",
  "--color-action-light-contrast": "var(--color-white)",
  "--color-action-dark-contrast": "var(--color-white)",
  "--color-highlight": "var(--color-secondary)",
  "--color-highlight-light": "oklch(from var(--color-highlight) calc(l + 0.15) c h)",
  "--color-highlight-dark": "oklch(from var(--color-highlight) calc(l - 0.15) c h)",
  "--color-highlight-light-contrast": "var(--color-white)",
  "--color-highlight-dark-contrast": "var(--color-white)",
  "--color-success": "var(--color-green)",
  "--color-success-light": "oklch(from var(--color-success) calc(l + 0.15) c h)",
  "--color-success-dark": "oklch(from var(--color-success) calc(l - 0.15) c h)",
  "--color-success-light-contrast": "var(--color-white)",
  "--color-success-dark-contrast": "var(--color-white)",
  "--color-warning": "var(--color-yellow)",
  "--color-warning-light": "oklch(from var(--color-warning) calc(l + 0.15) c h)",
  "--color-warning-dark": "oklch(from var(--color-warning) calc(l - 0.15) c h)",
  "--color-warning-light-contrast": "var(--color-white)",
  "--color-warning-dark-contrast": "var(--color-white)",
  "--color-error": "var(--color-red)",
  "--color-error-light": "oklch(from var(--color-error) calc(l + 0.15) c h)",
  "--color-error-dark": "oklch(from var(--color-error) calc(l - 0.15) c h)",
  "--color-error-light-contrast": "var(--color-white)",
  "--color-error-dark-contrast": "var(--color-white)",
  "--color-surface": "light-dark(var(--color-white), var(--color-neutral-9))",
  "--color-surface-raised": "light-dark(var(--color-neutral-0), var(--color-neutral-8))",
  "--color-text-primary": "light-dark(var(--color-neutral-8), var(--color-neutral-1))",
  "--color-text-secondary": "light-dark(var(--color-neutral-6), var(--color-neutral-3))",
  "--color-text-tertiary": "light-dark(var(--color-secondary), var(--color-secondary-light))",
  "--color-text-body": "light-dark(var(--color-neutral-8), var(--color-neutral-2))",
  "--color-border": "light-dark(var(--color-neutral-3), var(--color-neutral-7))",
  "--color-viewport-background": "light-dark(var(--color-white), var(--color-neutral-10))",
  "--font-primary-stack": "\"Geist\", system-ui, -apple-system, \"Segoe UI\", roboto, \"Helvetica Neue\", arial, sans-serif",
  "--font-secondary-stack": "var(--font-primary-stack)",
  "--font-tertiary-stack": "ui-monospace, \"Cascadia Code\", \"Source Code Pro\", menlo, consolas, \"DejaVu Sans Mono\", monospace",
  "--font-family": "var(--font-primary-stack)",
  "--font-family-heading": "var(--font-secondary-stack)",
  "--font-weight-thin": "100",
  "--font-weight-extra-light": "200",
  "--font-weight-light": "300",
  "--font-weight-normal": "400",
  "--font-weight-medium": "500",
  "--font-weight-semi-bold": "600",
  "--font-weight-bold": "700",
  "--font-weight-extra-bold": "800",
  "--font-weight-black": "900",
  "--type-ratio": "1.333",
  "--font-size-base": "clamp(1rem, 0.95rem + 0.25vw, 1.125rem)",
  "--font-size-h6": "calc(var(--font-size-base) / var(--type-ratio))",
  "--font-size-h5": "var(--font-size-base)",
  "--font-size-h4": "calc(var(--font-size-base) * var(--type-ratio))",
  "--font-size-h3": "calc(var(--font-size-base) * pow(var(--type-ratio), 2))",
  "--font-size-h2": "calc(var(--font-size-base) * pow(var(--type-ratio), 3))",
  "--font-size-h1": "calc(var(--font-size-base) * pow(var(--type-ratio), 4))",
  "--font-size-display": "calc(var(--font-size-base) * pow(var(--type-ratio), 5))",
  "--font-weight-heading": "var(--font-weight-semi-bold)",
  "--font-size-body": "var(--font-size-base)",
  "--font-size-body-sm": "calc(var(--font-size-base) * 0.75)",
  "--font-size-body-lg": "calc(var(--font-size-base) * 1.25)",
  "--line-height-reset": "1",
  "--line-height-text": "1.5",
  "--line-height-heading": "1.25",
  "--spacing-base": "clamp(1.5rem, 1.25rem + 1.25vw, 2.5rem)",
  "--spacing-xs": "calc(var(--spacing-base) * 0.375)",
  "--spacing-sm": "calc(var(--spacing-base) * 0.5)",
  "--spacing-md": "var(--spacing-base)",
  "--spacing-lg": "calc(var(--spacing-base) * 1.5)",
  "--spacing-xl": "calc(var(--spacing-base) * 2)",
  "--linear": "cubic-bezier(0.250, 0.250, 0.750, 0.750)",
  "--ease": "cubic-bezier(0.250, 0.100, 0.250, 1.000)",
  "--ease-in": "cubic-bezier(0.420, 0.000, 1.000, 1.000)",
  "--ease-out": "cubic-bezier(0.000, 0.000, 0.580, 1.000)",
  "--ease-in-out": "cubic-bezier(0.420, 0.000, 0.580, 1.000)",
  "--ease-in-quad": "cubic-bezier(0.550, 0.085, 0.680, 0.530)",
  "--ease-in-cubic": "cubic-bezier(0.550, 0.055, 0.675, 0.190)",
  "--ease-in-quart": "cubic-bezier(0.895, 0.030, 0.685, 0.220)",
  "--ease-in-quint": "cubic-bezier(0.755, 0.050, 0.855, 0.060)",
  "--ease-in-sine": "cubic-bezier(0.470, 0.000, 0.745, 0.715)",
  "--ease-in-expo": "cubic-bezier(0.950, 0.050, 0.795, 0.035)",
  "--ease-in-circ": "cubic-bezier(0.600, 0.040, 0.980, 0.335)",
  "--ease-in-back": "cubic-bezier(0.600, -0.280, 0.735, 0.045)",
  "--ease-out-quad": "cubic-bezier(0.250, 0.460, 0.450, 0.940)",
  "--ease-out-cubic": "cubic-bezier(0.215, 0.610, 0.355, 1.000)",
  "--ease-out-quart": "cubic-bezier(0.165, 0.840, 0.440, 1.000)",
  "--ease-out-quint": "cubic-bezier(0.230, 1.000, 0.320, 1.000)",
  "--ease-out-sine": "cubic-bezier(0.390, 0.575, 0.565, 1.000)",
  "--ease-out-expo": "cubic-bezier(0.190, 1.000, 0.220, 1.000)",
  "--ease-out-circ": "cubic-bezier(0.075, 0.820, 0.165, 1.000)",
  "--ease-out-back": "cubic-bezier(0.175, 0.885, 0.320, 1.275)",
  "--ease-in-out-quad": "cubic-bezier(0.455, 0.030, 0.515, 0.955)",
  "--ease-in-out-cubic": "cubic-bezier(0.645, 0.045, 0.355, 1.000)",
  "--ease-in-out-quart": "cubic-bezier(0.770, 0.000, 0.175, 1.000)",
  "--ease-in-out-quint": "cubic-bezier(0.860, 0.000, 0.070, 1.000)",
  "--ease-in-out-sine": "cubic-bezier(0.445, 0.050, 0.550, 0.950)",
  "--ease-in-out-expo": "cubic-bezier(1.000, 0.000, 0.000, 1.000)",
  "--ease-in-out-circ": "cubic-bezier(0.785, 0.135, 0.150, 0.860)",
  "--ease-in-out-back": "cubic-bezier(0.680, -0.550, 0.265, 1.550)",
  "--animation-duration": "0.5s",
  "--animation-duration-slow": "calc(var(--animation-duration) * 2)",
  "--animation-duration-fast": "calc(var(--animation-duration) / 2)",
  "--animation-timing": "var(--ease-out-cubic)",
  "--border-width": "1px",
  "--border-style": "solid",
  "--border-color": "var(--color-border)",
  "--border-radius": "0.5rem",
  "--focus-outline-width": "2px",
  "--focus-outline-offset": "2px",
  "--elevation-1": "0 1px 2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.4)), 0 1px 3px 1px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.25))",
  "--elevation-2": "0 1px 2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.4)), 0 2px 6px 2px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.25))",
  "--elevation-3": "0 3px 9px 3px light-dark(rgb(0 0 0 / 0.06), rgb(0 0 0 / 0.3)), 0 1px 3px light-dark(rgb(0 0 0 / 0.15), rgb(0 0 0 / 0.4))",
  "--elevation-4": "0 2px 14px 4px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.3)), 0 2px 5px light-dark(rgb(0 0 0 / 0.15), rgb(0 0 0 / 0.4))",
  "--elevation-5": "0 8px 12px 6px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.3)), 0 4px 4px light-dark(rgb(0 0 0 / 0.15), rgb(0 0 0 / 0.4))",
  "--scrollbar-width": "5px",
  "--control-block-size-sm": "calc(var(--control-block-size) * 0.75)",
  "--control-block-size": "3rem",
  "--control-block-size-lg": "calc(var(--control-block-size) * 1.1875)",
  "--control-font-size": "calc(var(--font-size-body) * 0.875)",
  "--control-font-weight": "var(--font-weight-normal)",
  "--control-padding-inline-sm": "var(--spacing-xs)",
  "--control-padding-inline": "calc(var(--spacing-base) * 0.625)",
  "--control-padding-inline-lg": "calc(var(--spacing-base) * 0.875)",
};
