// AUTO-GENERATED — DO NOT EDIT
// Run `npm run generate:registry` to regenerate this file.

import type { TokenDefinition } from './types';

export const TOKEN_REGISTRY: TokenDefinition[] = [
  {
    key: "--color-action",
    label: "Action",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-primary)",
    subcategory: "Brand",
    derivedFrom: "--color-primary",
  },
  {
    key: "--color-action-dark",
    label: "Action Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-action) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-action",
  },
  {
    key: "--color-action-dark-contrast",
    label: "Action Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-action",
  },
  {
    key: "--color-action-light",
    label: "Action Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-action) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-action",
  },
  {
    key: "--color-action-light-contrast",
    label: "Action Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-action",
  },
  {
    key: "--color-black",
    label: "Black",
    type: "color",
    category: "colors",
    defaultValue: "#000",
    subcategory: "Palette",
  },
  {
    key: "--color-border",
    label: "Border Color",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-neutral-3), var(--color-neutral-7))",
    lightDark: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-error",
    label: "Error",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-red)",
    subcategory: "Brand",
    derivedFrom: "--color-red",
  },
  {
    key: "--color-error-dark",
    label: "Error Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-error) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-error",
  },
  {
    key: "--color-error-dark-contrast",
    label: "Error Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-error",
  },
  {
    key: "--color-error-light",
    label: "Error Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-error) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-error",
  },
  {
    key: "--color-error-light-contrast",
    label: "Error Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-error",
  },
  {
    key: "--color-green",
    label: "Green",
    type: "color",
    category: "colors",
    defaultValue: "#A3BE8C",
    subcategory: "Palette",
  },
  {
    key: "--color-highlight",
    label: "Highlight",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-secondary)",
    subcategory: "Brand",
    derivedFrom: "--color-secondary",
  },
  {
    key: "--color-highlight-dark",
    label: "Highlight Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-highlight) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-highlight",
  },
  {
    key: "--color-highlight-dark-contrast",
    label: "Highlight Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-highlight",
  },
  {
    key: "--color-highlight-light",
    label: "Highlight Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-highlight) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-highlight",
  },
  {
    key: "--color-highlight-light-contrast",
    label: "Highlight Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-highlight",
  },
  {
    key: "--color-neutral-0",
    label: "Neutral 0",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Palette",
    derivedFrom: "--color-white",
  },
  {
    key: "--color-neutral-1",
    label: "Neutral 1",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 10%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-10",
    label: "Neutral 10",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-black)",
    subcategory: "Palette",
    derivedFrom: "--color-black",
  },
  {
    key: "--color-neutral-2",
    label: "Neutral 2",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 20%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-3",
    label: "Neutral 3",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 30%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-4",
    label: "Neutral 4",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 40%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-5",
    label: "Neutral 5",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 50%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-6",
    label: "Neutral 6",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 60%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-7",
    label: "Neutral 7",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 70%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-8",
    label: "Neutral 8",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 80%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-neutral-9",
    label: "Neutral 9",
    type: "color",
    category: "colors",
    defaultValue: "color-mix(in oklch, var(--color-neutral-10) 90%, var(--color-white))",
    subcategory: "Palette",
    derivedFrom: "--color-neutral-10",
  },
  {
    key: "--color-primary",
    label: "Primary",
    type: "color",
    category: "colors",
    defaultValue: "#81A1C1",
    subcategory: "Brand",
  },
  {
    key: "--color-primary-dark",
    label: "Primary Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-primary) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-primary",
  },
  {
    key: "--color-primary-dark-contrast",
    label: "Primary Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-primary",
  },
  {
    key: "--color-primary-light",
    label: "Primary Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-primary) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-primary",
  },
  {
    key: "--color-primary-light-contrast",
    label: "Primary Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-primary",
  },
  {
    key: "--color-red",
    label: "Red",
    type: "color",
    category: "colors",
    defaultValue: "#BF616A",
    subcategory: "Palette",
  },
  {
    key: "--color-secondary",
    label: "Secondary",
    type: "color",
    category: "colors",
    defaultValue: "#B48EAD",
    subcategory: "Brand",
  },
  {
    key: "--color-secondary-dark",
    label: "Secondary Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-secondary) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-secondary",
  },
  {
    key: "--color-secondary-dark-contrast",
    label: "Secondary Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-secondary",
  },
  {
    key: "--color-secondary-light",
    label: "Secondary Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-secondary) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-secondary",
  },
  {
    key: "--color-secondary-light-contrast",
    label: "Secondary Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-secondary",
  },
  {
    key: "--color-success",
    label: "Success",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-green)",
    subcategory: "Brand",
    derivedFrom: "--color-green",
  },
  {
    key: "--color-success-dark",
    label: "Success Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-success) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-success",
  },
  {
    key: "--color-success-dark-contrast",
    label: "Success Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-success",
  },
  {
    key: "--color-success-light",
    label: "Success Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-success) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-success",
  },
  {
    key: "--color-success-light-contrast",
    label: "Success Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-success",
  },
  {
    key: "--color-surface",
    label: "Surface",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-white), var(--color-neutral-9))",
    lightDark: true,
    gradient: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-surface-raised",
    label: "Surface Raised",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-neutral-0), var(--color-neutral-8))",
    lightDark: true,
    gradient: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-tertiary",
    label: "Tertiary",
    type: "color",
    category: "colors",
    defaultValue: "#f1be5f",
    subcategory: "Brand",
  },
  {
    key: "--color-tertiary-dark",
    label: "Tertiary Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-tertiary) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-tertiary",
  },
  {
    key: "--color-tertiary-dark-contrast",
    label: "Tertiary Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-tertiary",
  },
  {
    key: "--color-tertiary-light",
    label: "Tertiary Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-tertiary) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-tertiary",
  },
  {
    key: "--color-tertiary-light-contrast",
    label: "Tertiary Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-tertiary",
  },
  {
    key: "--color-text-body",
    label: "Text Body",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-neutral-8), var(--color-neutral-2))",
    lightDark: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-text-primary",
    label: "Text Primary",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-neutral-8), var(--color-neutral-1))",
    lightDark: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-text-secondary",
    label: "Text Secondary",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-neutral-6), var(--color-neutral-3))",
    lightDark: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-text-tertiary",
    label: "Text Tertiary",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-secondary), var(--color-secondary-light))",
    lightDark: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-viewport-background",
    label: "Viewport Background",
    type: "color",
    category: "colors",
    defaultValue: "light-dark(var(--color-white), var(--color-neutral-10))",
    lightDark: true,
    gradient: true,
    subcategory: "Semantic",
  },
  {
    key: "--color-warning",
    label: "Warning",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-yellow)",
    subcategory: "Brand",
    derivedFrom: "--color-yellow",
  },
  {
    key: "--color-warning-dark",
    label: "Warning Dark",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-warning) calc(l - 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-warning",
  },
  {
    key: "--color-warning-dark-contrast",
    label: "Warning Dark Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-warning",
  },
  {
    key: "--color-warning-light",
    label: "Warning Light",
    type: "color",
    category: "colors",
    defaultValue: "oklch(from var(--color-warning) calc(l + 0.15) c h)",
    subcategory: "Brand",
    derivedFrom: "--color-warning",
  },
  {
    key: "--color-warning-light-contrast",
    label: "Warning Light Contrast",
    type: "color",
    category: "colors",
    defaultValue: "var(--color-white)",
    subcategory: "Brand",
    derivedFrom: "--color-warning",
  },
  {
    key: "--color-white",
    label: "White",
    type: "color",
    category: "colors",
    defaultValue: "#fff",
    subcategory: "Palette",
  },
  {
    key: "--color-yellow",
    label: "Yellow",
    type: "color",
    category: "colors",
    defaultValue: "#EBCB8B",
    subcategory: "Palette",
  },
  {
    key: "--font-family",
    label: "Font Family",
    type: "font",
    category: "typography",
    defaultValue: "var(--font-secondary-stack)",
  },
  {
    key: "--font-family-heading",
    label: "Heading Font Family",
    type: "font",
    category: "typography",
    defaultValue: "var(--font-family)",
  },
  {
    key: "--font-primary-stack",
    label: "Primary Font Stack",
    type: "font",
    category: "typography",
    defaultValue: "ui-serif, georgia, cambria, \"Times New Roman\", times, serif",
  },
  {
    key: "--font-secondary-stack",
    label: "Secondary Font Stack",
    type: "font",
    category: "typography",
    defaultValue: "system-ui, -apple-system, \"Segoe UI\", roboto, \"Helvetica Neue\", arial, sans-serif",
  },
  {
    key: "--font-size-base",
    label: "Font Size Base",
    type: "dimension",
    category: "typography",
    defaultValue: "clamp(1rem, 0.95rem + 0.25vw, 1.125rem)",
    min: 12,
    max: 24,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-body",
    label: "Font Size Body",
    type: "dimension",
    category: "typography",
    defaultValue: "var(--font-size-base)",
    min: 12,
    max: 24,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-body-lg",
    label: "Font Size Body LG",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * 1.25)",
    min: 14,
    max: 28,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-body-sm",
    label: "Font Size Body SM",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * 0.75)",
    min: 10,
    max: 20,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-display",
    label: "Font Size Display",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * pow(var(--type-ratio), 5))",
    min: 24,
    max: 128,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-h1",
    label: "Font Size H1",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * pow(var(--type-ratio), 4))",
    min: 16,
    max: 96,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-h2",
    label: "Font Size H2",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * pow(var(--type-ratio), 3))",
    min: 14,
    max: 72,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-h3",
    label: "Font Size H3",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * pow(var(--type-ratio), 2))",
    min: 12,
    max: 60,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-h4",
    label: "Font Size H4",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) * var(--type-ratio))",
    min: 12,
    max: 48,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-h5",
    label: "Font Size H5",
    type: "dimension",
    category: "typography",
    defaultValue: "var(--font-size-base)",
    min: 12,
    max: 36,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-size-h6",
    label: "Font Size H6",
    type: "dimension",
    category: "typography",
    defaultValue: "calc(var(--font-size-base) / var(--type-ratio))",
    min: 10,
    max: 24,
    step: 1,
    unit: "px",
  },
  {
    key: "--font-tertiary-stack",
    label: "Tertiary Font Stack",
    type: "font",
    category: "typography",
    defaultValue: "ui-monospace, \"Cascadia Code\", \"Source Code Pro\", menlo, consolas, \"DejaVu Sans Mono\", monospace",
  },
  {
    key: "--font-weight-black",
    label: "Weight Black",
    type: "weight",
    category: "typography",
    defaultValue: "900",
    hidden: true,
  },
  {
    key: "--font-weight-bold",
    label: "Weight Bold",
    type: "weight",
    category: "typography",
    defaultValue: "700",
    hidden: true,
  },
  {
    key: "--font-weight-extra-bold",
    label: "Weight Extra Bold",
    type: "weight",
    category: "typography",
    defaultValue: "800",
    hidden: true,
  },
  {
    key: "--font-weight-extra-light",
    label: "Weight Extra Light",
    type: "weight",
    category: "typography",
    defaultValue: "200",
    hidden: true,
  },
  {
    key: "--font-weight-heading",
    label: "Heading Weight",
    type: "weight",
    category: "typography",
    defaultValue: "var(--font-weight-bold)",
  },
  {
    key: "--font-weight-light",
    label: "Weight Light",
    type: "weight",
    category: "typography",
    defaultValue: "300",
    hidden: true,
  },
  {
    key: "--font-weight-medium",
    label: "Weight Medium",
    type: "weight",
    category: "typography",
    defaultValue: "500",
    hidden: true,
  },
  {
    key: "--font-weight-normal",
    label: "Weight Normal",
    type: "weight",
    category: "typography",
    defaultValue: "400",
    hidden: true,
  },
  {
    key: "--font-weight-semi-bold",
    label: "Weight Semi Bold",
    type: "weight",
    category: "typography",
    defaultValue: "600",
    hidden: true,
  },
  {
    key: "--font-weight-thin",
    label: "Weight Thin",
    type: "weight",
    category: "typography",
    defaultValue: "100",
    hidden: true,
  },
  {
    key: "--line-height-heading",
    label: "Line Height Heading",
    type: "dimension",
    category: "typography",
    defaultValue: "1.25",
    min: 0.8,
    max: 2.5,
    step: 0.05,
  },
  {
    key: "--line-height-reset",
    label: "Line Height Reset",
    type: "dimension",
    category: "typography",
    defaultValue: "1",
    min: 0.8,
    max: 2.5,
    step: 0.05,
  },
  {
    key: "--line-height-text",
    label: "Line Height Text",
    type: "dimension",
    category: "typography",
    defaultValue: "1.5",
    min: 0.8,
    max: 2.5,
    step: 0.05,
  },
  {
    key: "--type-ratio",
    label: "Type Ratio",
    type: "ratio",
    category: "typography",
    defaultValue: "1.414",
    min: 1.067,
    max: 1.618,
    step: 0.001,
  },
  {
    key: "--spacing-base",
    label: "Spacing Base",
    type: "dimension",
    category: "spacing",
    defaultValue: "clamp(1.5rem, 1.25rem + 1.25vw, 2.5rem)",
    min: 4,
    max: 32,
    step: 1,
    unit: "px",
  },
  {
    key: "--spacing-lg",
    label: "Spacing LG",
    type: "dimension",
    category: "spacing",
    defaultValue: "calc(var(--spacing-base) * 1.5)",
    min: 8,
    max: 64,
    step: 1,
    unit: "px",
  },
  {
    key: "--spacing-md",
    label: "Spacing MD",
    type: "dimension",
    category: "spacing",
    defaultValue: "var(--spacing-base)",
    min: 4,
    max: 32,
    step: 1,
    unit: "px",
  },
  {
    key: "--spacing-sm",
    label: "Spacing SM",
    type: "dimension",
    category: "spacing",
    defaultValue: "calc(var(--spacing-base) * 0.5)",
    min: 2,
    max: 24,
    step: 1,
    unit: "px",
  },
  {
    key: "--spacing-xl",
    label: "Spacing XL",
    type: "dimension",
    category: "spacing",
    defaultValue: "calc(var(--spacing-base) * 2)",
    min: 8,
    max: 96,
    step: 1,
    unit: "px",
  },
  {
    key: "--spacing-xs",
    label: "Spacing XS",
    type: "dimension",
    category: "spacing",
    defaultValue: "calc(var(--spacing-base) * 0.375)",
    min: 2,
    max: 16,
    step: 1,
    unit: "px",
  },
  {
    key: "--animation-duration",
    label: "Animation Duration",
    type: "duration",
    category: "animation",
    defaultValue: "0.5s",
    min: 0.05,
    max: 2,
    step: 0.05,
    unit: "s",
  },
  {
    key: "--animation-duration-fast",
    label: "Animation Duration Fast",
    type: "duration",
    category: "animation",
    defaultValue: "calc(var(--animation-duration) / 2)",
    derivedFrom: "--animation-duration",
    min: 0.01,
    max: 1,
    step: 0.01,
    unit: "s",
  },
  {
    key: "--animation-duration-slow",
    label: "Animation Duration Slow",
    type: "duration",
    category: "animation",
    defaultValue: "calc(var(--animation-duration) * 2)",
    derivedFrom: "--animation-duration",
    min: 0.1,
    max: 4,
    step: 0.05,
    unit: "s",
  },
  {
    key: "--animation-timing",
    label: "Animation Timing",
    type: "easing",
    category: "animation",
    defaultValue: "var(--ease-out-cubic)",
  },
  {
    key: "--ease",
    label: "Ease",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.250, 0.100, 0.250, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in",
    label: "Ease In",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.420, 0.000, 1.000, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in-back",
    label: "Ease In Back",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.600, -0.280, 0.735, 0.045)",
    hidden: true,
  },
  {
    key: "--ease-in-circ",
    label: "Ease In Circ",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.600, 0.040, 0.980, 0.335)",
    hidden: true,
  },
  {
    key: "--ease-in-cubic",
    label: "Ease In Cubic",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.550, 0.055, 0.675, 0.190)",
    hidden: true,
  },
  {
    key: "--ease-in-expo",
    label: "Ease In Expo",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.950, 0.050, 0.795, 0.035)",
    hidden: true,
  },
  {
    key: "--ease-in-out",
    label: "Ease In Out",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.420, 0.000, 0.580, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in-out-back",
    label: "Ease In Out Back",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.680, -0.550, 0.265, 1.550)",
    hidden: true,
  },
  {
    key: "--ease-in-out-circ",
    label: "Ease In Out Circ",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.785, 0.135, 0.150, 0.860)",
    hidden: true,
  },
  {
    key: "--ease-in-out-cubic",
    label: "Ease In Out Cubic",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.645, 0.045, 0.355, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in-out-expo",
    label: "Ease In Out Expo",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(1.000, 0.000, 0.000, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in-out-quad",
    label: "Ease In Out Quad",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.455, 0.030, 0.515, 0.955)",
    hidden: true,
  },
  {
    key: "--ease-in-out-quart",
    label: "Ease In Out Quart",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.770, 0.000, 0.175, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in-out-quint",
    label: "Ease In Out Quint",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.860, 0.000, 0.070, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-in-out-sine",
    label: "Ease In Out Sine",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.445, 0.050, 0.550, 0.950)",
    hidden: true,
  },
  {
    key: "--ease-in-quad",
    label: "Ease In Quad",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.550, 0.085, 0.680, 0.530)",
    hidden: true,
  },
  {
    key: "--ease-in-quart",
    label: "Ease In Quart",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.895, 0.030, 0.685, 0.220)",
    hidden: true,
  },
  {
    key: "--ease-in-quint",
    label: "Ease In Quint",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.755, 0.050, 0.855, 0.060)",
    hidden: true,
  },
  {
    key: "--ease-in-sine",
    label: "Ease In Sine",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.470, 0.000, 0.745, 0.715)",
    hidden: true,
  },
  {
    key: "--ease-out",
    label: "Ease Out",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.000, 0.000, 0.580, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-out-back",
    label: "Ease Out Back",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.175, 0.885, 0.320, 1.275)",
    hidden: true,
  },
  {
    key: "--ease-out-circ",
    label: "Ease Out Circ",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.075, 0.820, 0.165, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-out-cubic",
    label: "Ease Out Cubic",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.215, 0.610, 0.355, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-out-expo",
    label: "Ease Out Expo",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.190, 1.000, 0.220, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-out-quad",
    label: "Ease Out Quad",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.250, 0.460, 0.450, 0.940)",
    hidden: true,
  },
  {
    key: "--ease-out-quart",
    label: "Ease Out Quart",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.165, 0.840, 0.440, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-out-quint",
    label: "Ease Out Quint",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.230, 1.000, 0.320, 1.000)",
    hidden: true,
  },
  {
    key: "--ease-out-sine",
    label: "Ease Out Sine",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.390, 0.575, 0.565, 1.000)",
    hidden: true,
  },
  {
    key: "--linear",
    label: "Linear",
    type: "easing",
    category: "animation",
    defaultValue: "cubic-bezier(0.250, 0.250, 0.750, 0.750)",
    hidden: true,
  },
  {
    key: "--border-color",
    label: "Border Color",
    type: "color",
    category: "borders",
    defaultValue: "var(--color-border)",
    hidden: true,
  },
  {
    key: "--border-radius",
    label: "Border Radius",
    type: "dimension",
    category: "borders",
    defaultValue: "0.5rem",
    min: 0,
    max: 24,
    step: 1,
    unit: "px",
  },
  {
    key: "--border-style",
    label: "Border Style",
    type: "border-style",
    category: "borders",
    defaultValue: "solid",
  },
  {
    key: "--border-width",
    label: "Border Width",
    type: "dimension",
    category: "borders",
    defaultValue: "1px",
    min: 0,
    max: 8,
    step: 1,
    unit: "px",
  },
  {
    key: "--focus-outline-offset",
    label: "Focus Outline Offset",
    type: "dimension",
    category: "borders",
    defaultValue: "2px",
    min: 0,
    max: 8,
    step: 1,
    unit: "px",
  },
  {
    key: "--focus-outline-width",
    label: "Focus Outline Width",
    type: "dimension",
    category: "borders",
    defaultValue: "2px",
    min: 1,
    max: 6,
    step: 1,
    unit: "px",
  },
  {
    key: "--elevation-1",
    label: "Elevation 1",
    type: "shadow",
    category: "elevation",
    defaultValue: "0 1px 2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.4)), 0 1px 3px 1px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.25))",
  },
  {
    key: "--elevation-2",
    label: "Elevation 2",
    type: "shadow",
    category: "elevation",
    defaultValue: "0 1px 2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.4)), 0 2px 6px 2px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.25))",
  },
  {
    key: "--elevation-3",
    label: "Elevation 3",
    type: "shadow",
    category: "elevation",
    defaultValue: "0 3px 9px 3px light-dark(rgb(0 0 0 / 0.06), rgb(0 0 0 / 0.3)), 0 1px 3px light-dark(rgb(0 0 0 / 0.15), rgb(0 0 0 / 0.4))",
  },
  {
    key: "--elevation-4",
    label: "Elevation 4",
    type: "shadow",
    category: "elevation",
    defaultValue: "0 2px 14px 4px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.3)), 0 2px 5px light-dark(rgb(0 0 0 / 0.15), rgb(0 0 0 / 0.4))",
  },
  {
    key: "--elevation-5",
    label: "Elevation 5",
    type: "shadow",
    category: "elevation",
    defaultValue: "0 8px 12px 6px light-dark(rgb(0 0 0 / 0.08), rgb(0 0 0 / 0.3)), 0 4px 4px light-dark(rgb(0 0 0 / 0.15), rgb(0 0 0 / 0.4))",
  },
  {
    key: "--control-block-size",
    label: "Control Block Size",
    type: "dimension",
    category: "controls",
    defaultValue: "3rem",
  },
  {
    key: "--control-block-size-lg",
    label: "Control Block Size LG",
    type: "dimension",
    category: "controls",
    defaultValue: "calc(var(--control-block-size) * 1.1875)",
  },
  {
    key: "--control-block-size-sm",
    label: "Control Block Size SM",
    type: "dimension",
    category: "controls",
    defaultValue: "calc(var(--control-block-size) * 0.75)",
  },
  {
    key: "--control-font-size",
    label: "Control Font Size",
    type: "dimension",
    category: "controls",
    defaultValue: "calc(var(--font-size-body) * 0.875)",
    min: 10,
    max: 20,
    step: 1,
    unit: "px",
  },
  {
    key: "--control-font-weight",
    label: "Control Font Weight",
    type: "weight",
    category: "controls",
    defaultValue: "var(--font-weight-normal)",
  },
  {
    key: "--control-padding-inline",
    label: "Control Padding Inline",
    type: "dimension",
    category: "controls",
    defaultValue: "calc(var(--spacing-base) * 0.625)",
    min: 8,
    max: 32,
    step: 1,
    unit: "px",
  },
  {
    key: "--control-padding-inline-lg",
    label: "Control Padding Inline LG",
    type: "dimension",
    category: "controls",
    defaultValue: "calc(var(--spacing-base) * 0.875)",
    min: 12,
    max: 48,
    step: 1,
    unit: "px",
  },
  {
    key: "--control-padding-inline-sm",
    label: "Control Padding Inline SM",
    type: "dimension",
    category: "controls",
    defaultValue: "var(--spacing-xs)",
    min: 4,
    max: 24,
    step: 1,
    unit: "px",
  },
  {
    key: "--scrollbar-width",
    label: "Scrollbar Width",
    type: "dimension",
    category: "controls",
    defaultValue: "5px",
    min: 2,
    max: 16,
    step: 1,
    unit: "px",
  },
];

export const TOKEN_REGISTRY_MAP: Record<string, TokenDefinition> = Object.fromEntries(
  TOKEN_REGISTRY.map((token) => [token.key, token])
);
